#!/usr/bin/env python3
"""
Generate a fictional 14-day access log for todo-app.

Deterministic: the same seed always produces the same CSV and the same answer key.

    python3 docs/data/make_access_log.py

Writes docs/data/todo-access-log.csv and docs/data/ANSWER-KEY.md next to this script.
"""
import csv
import random
from collections import Counter, defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path

SEED = 20260907
START = date(2026, 9, 7)  # a Monday
DAYS = 14

FIRST = ["ada", "ben", "cara", "dev", "ella", "finn", "gus", "hana", "ivy", "jack",
         "kit", "leo", "mia", "noor", "omar", "pia", "quinn", "rae", "sam", "tess",
         "uma", "vic", "wren", "xan", "yara", "zed", "amir", "bea", "cole", "dot",
         "eli", "fay", "gem", "hal", "isla", "jo", "kai", "lou", "max", "nell"]
USERS = [f"{name}.{suffix}" for name, suffix in zip(FIRST, ["mf"] * len(FIRST))]

# (method, path template, weight, typical status distribution)
ROUTES = [
    ("GET", "/api/todos", 40, [(200, 99), (500, 1)]),
    ("GET", "/api/todos?done=false", 12, [(200, 100)]),
    ("GET", "/api/todos?done=true", 5, [(200, 100)]),
    ("GET", "/api/todos/{id}", 8, [(200, 90), (404, 10)]),
    ("POST", "/api/todos", 14, [(201, 97), (400, 3)]),
    ("POST", "/api/todos/{id}/toggle", 12, [(200, 95), (404, 5)]),
    ("PUT", "/api/todos/{id}", 3, [(200, 92), (404, 8)]),
    ("DELETE", "/api/todos/{id}", 4, [(204, 93), (404, 7)]),
    ("GET", "/api/health", 2, [(200, 100)]),
]

# Requests per day: weekdays busy, weekend quiet.
WEEKDAY_VOLUME = [52, 58, 61, 55, 44]  # Mon..Fri
WEEKEND_VOLUME = [9, 6]                # Sat, Sun


def pick_weighted(pairs, rnd):
    total = sum(w for _, w in pairs)
    r = rnd.uniform(0, total)
    upto = 0
    for item, w in pairs:
        upto += w
        if r <= upto:
            return item
    return pairs[-1][0]


def working_hour(rnd, weekend):
    if weekend:
        return rnd.randint(9, 17)
    # Two humps: morning and mid-afternoon.
    return pick_weighted([(8, 4), (9, 10), (10, 12), (11, 10), (12, 5), (13, 6),
                          (14, 10), (15, 11), (16, 8), (17, 4), (18, 1)], rnd)


def main():
    rnd = random.Random(SEED)
    here = Path(__file__).resolve().parent
    rows = []
    for offset in range(DAYS):
        day = START + timedelta(days=offset)
        weekend = day.weekday() >= 5
        volume = WEEKEND_VOLUME[day.weekday() - 5] if weekend else WEEKDAY_VOLUME[day.weekday()]
        volume += rnd.randint(-4, 4)
        # Weekend: a handful of users. Weekday: most of the team.
        active = rnd.sample(USERS, rnd.randint(3, 6) if weekend else rnd.randint(22, 34))
        for _ in range(volume):
            user = rnd.choice(active)
            method, template, _, statuses = pick_weighted([(r, r[2]) for r in ROUTES], rnd)
            path = template.replace("{id}", str(rnd.randint(1, 60)))
            status = pick_weighted(statuses, rnd)
            hour = working_hour(rnd, weekend)
            ts = datetime(day.year, day.month, day.day, hour, rnd.randint(0, 59), rnd.randint(0, 59))
            base = {"GET": 12, "POST": 25, "PUT": 22, "DELETE": 18}[method]
            latency = max(3, int(rnd.gauss(base, base / 3)))
            if status >= 500:
                latency = rnd.randint(800, 2400)
            rows.append((ts, user, method, path, status, latency))
    rows.sort(key=lambda r: r[0])

    csv_path = here / "todo-access-log.csv"
    with csv_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["timestamp", "user", "method", "path", "status", "latency_ms"])
        for ts, user, method, path, status, latency in rows:
            w.writerow([ts.strftime("%Y-%m-%dT%H:%M:%S"), user, method, path, status, latency])

    # Answer key
    per_day = Counter(r[0].date() for r in rows)
    users_per_day = defaultdict(set)
    for r in rows:
        users_per_day[r[0].date()].add(r[1])
    unique_users = len({r[1] for r in rows})
    by_status = Counter(r[4] for r in rows)
    by_method = Counter(r[2] for r in rows)
    errors = sum(1 for r in rows if r[4] >= 400)
    server_errors = sum(1 for r in rows if r[4] >= 500)
    top_users = Counter(r[1] for r in rows).most_common(5)
    latencies = sorted(r[5] for r in rows)
    p50 = latencies[len(latencies) // 2]
    p95 = latencies[int(len(latencies) * 0.95)]
    busiest = max(per_day.items(), key=lambda kv: kv[1])
    quietest = min(per_day.items(), key=lambda kv: kv[1])

    lines = [
        "# Answer key: docs/data/todo-access-log.csv",
        "",
        f"Generated by `make_access_log.py` with seed {SEED}. Do not hand this out before Part 4.",
        "",
        "## Totals",
        "",
        f"- Requests: **{len(rows)}**",
        f"- Unique users: **{unique_users}**",
        f"- Period: {START.isoformat()} to {(START + timedelta(days=DAYS - 1)).isoformat()} ({DAYS} days)",
        f"- Busiest day: {busiest[0].isoformat()} ({busiest[0].strftime('%A')}) with {busiest[1]} requests",
        f"- Quietest day: {quietest[0].isoformat()} ({quietest[0].strftime('%A')}) with {quietest[1]} requests",
        f"- Requests with status >= 400: {errors} ({errors / len(rows):.1%}); status >= 500: {server_errors}",
        f"- Latency: median {p50} ms, p95 {p95} ms",
        "",
        "## Per day",
        "",
        "| Date | Day | Requests | Distinct users |",
        "|------|-----|---------:|---------------:|",
    ]
    for d in sorted(per_day):
        lines.append(f"| {d.isoformat()} | {d.strftime('%a')} | {per_day[d]} | {len(users_per_day[d])} |")
    lines += ["", "## By method", "", "| Method | Requests |", "|--------|---------:|"]
    for m, n in sorted(by_method.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {m} | {n} |")
    lines += ["", "## By status", "", "| Status | Requests |", "|--------|---------:|"]
    for s, n in sorted(by_status.items()):
        lines.append(f"| {s} | {n} |")
    lines += ["", "## Top 5 users", "", "| User | Requests |", "|------|---------:|"]
    for u, n in top_users:
        lines.append(f"| {u} | {n} |")
    lines.append("")
    (here / "ANSWER-KEY.md").write_text("\n".join(lines))
    print(f"wrote {csv_path.name}: {len(rows)} rows, {unique_users} users")


if __name__ == "__main__":
    main()
